version: '3'

services:
  database:
    container_name: mongoecom
    image: mongo:latest
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - ./.docker/mongodb/data/db/:/data/db/
      - ./.docker/mongodb/data/log/:/var/log/mongodb/
    env_file:
      - .env
    environment:
      - MONGO_INITDB_DATABASE=${DATABASE_DB}
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MONGO_INITDB_USERNAME=${DATABASE_SERVICE_USERNAME}
      - MONGO_INITDB_PASSWORD=${DATABASE_SERVICE_PASSWORD}
    ports:
      - '${DB_PORT_RANGE_START}-${DB_PORT_RANGE_END}:${DB_PORT_RANGE_START}-${DB_PORT_RANGE_END}'
